import { createHash } from "node:crypto";
import { readFile, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { build } from "esbuild";

const directory = dirname(fileURLToPath(import.meta.url));
const output = join(tmpdir(), `memmy-workspace-bridge-${process.pid}.mjs`);
try {
  await build({
    entryPoints: [join(directory, "runtime.ts")],
    outfile: output,
    bundle: true,
    platform: "node",
    target: "node20",
    format: "esm",
    sourcemap: false,
    minify: false,
    legalComments: "none",
    packages: "bundle",
    banner: {
      js: 'import { createRequire as __memmyCreateRequire } from "node:module"; const require = __memmyCreateRequire(import.meta.url);',
    },
    logLevel: "silent",
  });
  const asset = await readFile(output, "utf8");
  const bareImports = [...asset.matchAll(/(?:from\s+|import\s*)["']([^"']+)["']/gu)]
    .map((match) => match[1])
    .filter((specifier) => !specifier.startsWith("node:"));
  if (bareImports.length) throw new Error(`Workspace Bridge asset contains bare imports: ${bareImports.join(", ")}`);
  const hash = createHash("sha256").update(asset).digest("hex");
  const source = [
    "/** Generated by workspace-bridge/build-runtime.mjs. Do not edit by hand. */",
    `export const MEMMY_WORKSPACE_BRIDGE_RUNTIME_SHA256 = ${JSON.stringify(hash)};`,
    `export const MEMMY_WORKSPACE_BRIDGE_RUNTIME_ASSET = ${JSON.stringify(asset)};`,
    "",
  ].join("\n");
  await writeFile(join(directory, "runtime-asset.ts"), source, "utf8");
} finally {
  await rm(output, { force: true });
}
